// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaFFoUOq3aj1IgnzU8uJ2pLJB2Nav8htc',
    appId: '1:351630912116:web:f3e1f54cd257565154bf21',
    messagingSenderId: '351630912116',
    projectId: 'weather-app-3951b',
    authDomain: 'weather-app-3951b.firebaseapp.com',
    storageBucket: 'weather-app-3951b.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCj6edIER9eNo-pHYdNbjaCbZvfoYkFukg',
    appId: '1:351630912116:android:d5127ead9a26a67a54bf21',
    messagingSenderId: '351630912116',
    projectId: 'weather-app-3951b',
    storageBucket: 'weather-app-3951b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAy_Mjp-C2XS3Lcy7gQqOHeVOpoSHQG7U',
    appId: '1:351630912116:ios:66794468beb5c23854bf21',
    messagingSenderId: '351630912116',
    projectId: 'weather-app-3951b',
    storageBucket: 'weather-app-3951b.firebasestorage.app',
    iosClientId: '351630912116-612felkkinvm26epnfvcl9e1td7fpc5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBAy_Mjp-C2XS3Lcy7gQqOHeVOpoSHQG7U',
    appId: '1:351630912116:ios:66794468beb5c23854bf21',
    messagingSenderId: '351630912116',
    projectId: 'weather-app-3951b',
    storageBucket: 'weather-app-3951b.firebasestorage.app',
    iosClientId: '351630912116-612felkkinvm26epnfvcl9e1td7fpc5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaFFoUOq3aj1IgnzU8uJ2pLJB2Nav8htc',
    appId: '1:351630912116:web:4fde606843ad042a54bf21',
    messagingSenderId: '351630912116',
    projectId: 'weather-app-3951b',
    authDomain: 'weather-app-3951b.firebaseapp.com',
    storageBucket: 'weather-app-3951b.firebasestorage.app',
  );
}
